import { Dimensions, StyleSheet } from "react-native";
const homestyle = StyleSheet.create({
  welcome: {
    fontSize: 37,
    fontWeight: "700",
    marginTop: 5,
    color: "#000000",
    marginLeft: 35,
    marginRight: 15,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#6A4029",
    padding: 20,
    marginLeft: 25,
    marginRight: 25,
    marginTop: 5,
    borderRadius: 15,
  },
  text: {
    fontSize: 16,
    color: "#FFFFFF",
  },
  textprimary: {
    fontSize: 16,
    color: "#6A4029",
    marginLeft: 35,
    marginRight: 35,
    marginTop: 15,
    fontWeight: "700",
    borderBottomColor: "#6A4029",
    borderBottomWidth: 2,
  },
  textsecondary: {
    fontSize: 13,
    color: "#6A4029",
    marginLeft: 35,
    marginRight: 5,
    marginBottom: 10,
    fontWeight: "700",
    textAlign: "right",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 15,
    marginLeft: 35,
    marginRight: 35,
    marginTop: 10,
    borderRadius: 30,
    fontWeight: "900",
  },
  title: {
    fontSize: 34,
    color: "#333",
    fontWeight: "700",
    marginTop: "15%",
  },
  productTitle: {
    fontWeight: "900",
    fontSize: 22.29,
    color: "#333",
  },
  productPrice: {
    color: "#6A4029",
    fontSize: 17,
    fontWeight: "700",
  },
  sectionTitle: {
    color: "#6A4029",
    fontSize: 17,
    fontWeight: "700",
  },
  cardWrap: {
    width: Dimensions.get("window").width / 1.5,
    // width: '66.66%',
    // marginLeft: 15,
    padding: 15,
    alignItems: "center",
  },
  card: {
    backgroundColor: "#fff",
    height: 250,
    elevation: 7,
    width: "100%",
    borderRadius: 30,
    marginTop: 15,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  navbar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 50,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#ccc",
  },
});

export default homestyle;
